# 命令行 java -jar **.jar --spring.profiles.active=xxx 启动不同配置文件

spring:
  application:
    name: author

server:
  port: 20002

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka/