eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10000/eureka/
server:
  port: 10002
spring:
  application:
    name: service-feign

# 打开feign自带断路器
feign:
  hystrix:
    enabled: true