server:
  port: 10001
spring:
  application:
    name: zuul-gateway
zuul:
  routes:
    # 将/author/** 路径的请求转发给author服务
    author:
      path: /api-a/**
      serviceID: author
    # 将/book/** 路径的请求转发给author服务
    book:
      path: /api-b/**
      serviceID: book
  # 所有请求必须加上前缀 ， eg. http://localhost:10001/api/book/index
  prefix: /api
  # 屏蔽路径，比如说不想给/hello/**的路径进行路由
  ignored-patterns: /hello/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka/